### ISSUE TITLE
1.9.1 not published on Deno

### ISSUE THREAD

**Issue by Schotsl** [manyuanrong/sql-builder#20]
Here I am again, @manyuanrong released v1.9.1 this morning, but for some reason the package hasn't been published on deno.land (https://deno.land/x/sql_builder@v1.9.1). Maybe it has too do with the hotfix numbering?

I asked the Deno Discord and got this response:

**Tags should get pushed. Check your webhook on GitHub. If it doesn't show a recent request for the new tag, it's a webhook configuration issue. It should show the response it got. If it's a success response, check the status link in the response for more detail.**

So could you share the webhook response for debugging? :)

**Comment by manyuanrong** [comment]
![image](https://user-images.githubusercontent.com/7514524/134443703-0424c86b-3bd0-4e6b-adff-2932ed9b6b10.png)
The most recent webhook triggered timed out. I think it was because the deno registry service was unavailable at that time.

I have re-triggered this webhook
