### ISSUE TITLE
`replaceParams` throw strange errors with unsupported objects

### ISSUE THREAD

**Issue by GunseiKPaseri** [manyuanrong/sql-builder#21]
I get a strange error when I run something like the following
```
replaceParams("SELECT data FROM xxx WHERE id = ?", [somePromiseObject])
```
like this
```
TypeError - str.replaceAll is not a function
    at escapeString (https://deno.land/x/sql_builder@v1.9.1/util.ts:83:14)
    at https://deno.land/x/sql_builder@v1.9.1/util.ts:43:20
....
```
Because 
https://github.com/manyuanrong/sql-builder/blob/2b2b5dea7ce1b3fd37a349446279f6dbef6bb23a/util.ts#L37-L43
there is no `break;` or `throw new Error("~~~")`.

Hopefully it will be strictly type specific without using `any` as an argument.
At the very least, I'd like it to throw an error about what kind of input would be problematic here.

**Comment by Pietrek14** [comment]
@manyuanrong As it is now solved, could you close?
